### PR TITLE
fix Kubernetes minor server version

### LINKED ISSUE #5: failed to unmarshal extension properties: invalid character ':' after top-level value (404: Not Found)
When running it against an AWS EKS 1.19 cluster I get the following error:

```shell
❯ ./bin/kubedd --target-kubernetes-version 1.20
ERR  - failed to unmarshal extension properties: invalid character ':' after top-level value (404: Not Found)

Results for cluster at version 1.19+ to 1.20
-------------------------------------------
>>>> Deprecated API Version's <<<<
...
```

The tool seems to work though, so I'm not sure what the error actually means.

Built from source with `make build` from commit `086224d8d4ec6fe2ddf753bc872250e5afcd6cb5`.

### PR DESCRIPTION
**Pull request by wrdls**
AWS EKS clusters report their Kubernetes minor version as "19+".

Fixes #5

### CODE REVIEW

**Review by pghildiyal — APPROVED** [review]

File: pkg/Cluster.go [hunk 1]
```diff
@@ -64,7 +65,7 @@ func (c *Cluster) ServerVersion() (string, error) {
 	if err != nil {
 		return "", err
 	}
-	return fmt.Sprintf("%s.%s", info.Major, info.Minor), nil
+	return fmt.Sprintf("%s.%s", info.Major, strings.Trim(info.Minor, "+")), nil
```
Comment (pghildiyal) [inline pkg/Cluster.go:68]: Should we use regex (\d+)([^\d]*) instead? this will make it agnostic to any other trailing characters also.

Comment (wrdls) [reply pkg/Cluster.go:68]: What about parsing from `info.GitVersion` instead as I suggested in https://github.com/devtron-labs/silver-surfer/issues/5#issuecomment-929249098?

Seems like it will be more stable.

I don't have a GKE cluster to test on but they seem to be following a similar format: https://cloud.google.com/kubernetes-engine/versioning

So something like this:

```go
gitVersion := strings.Split(info.GitVersion, ".")
major := strings.Trim(gitVersion[0], "v")
minor := gitVersion[1]
return fmt.Sprintf("%s.%s", major, minor), nil
```

Comment (pghildiyal) [reply pkg/Cluster.go:68]: Yes, gitVersion appears to be better indicator, lets use this instead
